### ISSUE TITLE
docs: reorganize the tutorials tab

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8197]
### Please describe the issue

I took a stab at this for https://github.com/ibis-project/ibis/pull/8085 and it did not go well. the issue is reorganizing the tutorials requires running all of them from scratch:

- R setup w/ a bunch of packages for that tutorial
- hit some issue w/ the pandas tutorial
- need Starburst Galaxy setup for that tutorial
- need Flink/Kafka things setup for that tutorial

running those all at once is going to take some time. I propose we merge #8085 as-is (w/ some minor requested changes) and work to reorganize the tutorials later (i.e. someone else do this please 😄) 

per discussion, the ideal structure should be:

```yaml
  sidebar:
    - id: ""
    - id: getting-started
      title: "Getting started"
      style: "docked"
      collapse-level: 2
      contents:
        - install.qmd
        - auto: tutorials/basics
        - auto: tutorials/ibis-for-x
        - auto: tutorials/backends
```

where `basics` contains `getting_started.qmd` (should also rename to `getting-started.qmd` for consistency), `ibis-for-x` contains those tutorials (and the new PySpark one in #8090), and `backends` contains backend-specific tutorials (Starburst Galaxy and Apache Flink for now)

we would also need to add redirects for all of these

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
